import type { Product } from "./product.types";

export const mockProducts: Product[] = [
  {
    id: "mock-product-001",
    platform: "tmall",
    source: "mock",
    outerItemId: "tmall-mock-100001",
    title: "家用智能恒温电热水壶 1.7L 大容量 304 不锈钢内胆",
    shortTitle: "智能恒温电热水壶",
    description: "适合日常泡茶、冲奶和办公使用，支持多档保温，内胆材质清晰可查。",
    mainImage: "https://placehold.co/800x800?text=Electric+Kettle",
    price: 169,
    finalPrice: 129,
    couponAmount: 40,
    commissionRate: 8.5,
    shopName: "天猫品质生活旗舰店",
    categoryId: "cat-home-appliance",
    categorySlug: "cat-home-appliance",
    categoryName: "家用电器",
    promotionUrl: "https://example.com/promotion/mock-product-001",
    couponUrl: "https://example.com/coupon/mock-product-001",
    status: "active",
    createdAt: "2026-06-20T08:00:00.000Z",
    updatedAt: "2026-06-20T08:00:00.000Z",
  },
  {
    id: "mock-product-002",
    platform: "taobao",
    source: "mock",
    outerItemId: "taobao-mock-100002",
    title: "夏季男士速干短袖 T 恤 透气运动休闲上衣",
    shortTitle: "男士速干短袖 T 恤",
    description: "轻薄速干面料，适合通勤、健身和日常休闲场景，尺码覆盖较全。",
    mainImage: "https://placehold.co/800x800?text=Quick+Dry+Tshirt",
    price: 79,
    finalPrice: 49,
    couponAmount: 30,
    commissionRate: 12,
    shopName: "淘宝运动服饰店",
    categoryId: "cat-fashion",
    categorySlug: "cat-fashion",
    categoryName: "服饰鞋包",
    promotionUrl: "https://example.com/promotion/mock-product-002",
    couponUrl: "https://example.com/coupon/mock-product-002",
    status: "active",
    createdAt: "2026-06-20T08:05:00.000Z",
    updatedAt: "2026-06-20T08:05:00.000Z",
  },
  {
    id: "mock-product-003",
    platform: "jd",
    source: "mock",
    outerItemId: "jd-mock-100003",
    title: "人体工学办公椅 久坐护腰可调节电脑椅",
    shortTitle: "人体工学办公椅",
    description: "腰托、扶手和椅背支持多档调节，适合居家办公和长时间电脑使用。",
    mainImage: "https://placehold.co/800x800?text=Office+Chair",
    price: 699,
    finalPrice: 599,
    couponAmount: 100,
    commissionRate: 5.8,
    shopName: "京东家居自营专区",
    categoryId: "cat-home",
    categorySlug: "cat-home",
    categoryName: "办公好物",
    promotionUrl: "https://example.com/promotion/mock-product-003",
    couponUrl: "https://example.com/coupon/mock-product-003",
    status: "active",
    createdAt: "2026-06-20T08:10:00.000Z",
    updatedAt: "2026-06-20T08:10:00.000Z",
  },
  {
    id: "mock-product-004",
    platform: "vip",
    source: "mock",
    outerItemId: "vip-mock-100004",
    title: "女士轻便通勤双肩包 防泼水大容量电脑背包",
    shortTitle: "女士通勤双肩包",
    description: "通勤友好容量，支持放入常见尺寸笔记本电脑，外层防泼水便于日常出行。",
    mainImage: "https://placehold.co/800x800?text=Commuter+Backpack",
    price: 239,
    finalPrice: 159,
    couponAmount: 80,
    commissionRate: 10.2,
    shopName: "唯品会箱包精选",
    categoryId: "cat-bag",
    categorySlug: "cat-bag",
    categoryName: "箱包配饰",
    promotionUrl: "https://example.com/promotion/mock-product-004",
    couponUrl: "https://example.com/coupon/mock-product-004",
    status: "active",
    createdAt: "2026-06-20T08:15:00.000Z",
    updatedAt: "2026-06-20T08:15:00.000Z",
  },
  {
    id: "mock-product-005",
    platform: "tmall",
    source: "mock",
    outerItemId: "tmall-mock-100005",
    title: "儿童护眼 LED 台灯 国 AA 级照度 学习阅读灯",
    shortTitle: "儿童护眼 LED 台灯",
    description: "适合书桌学习场景，支持亮度调节和定时提醒，导购内容可重点说明照度与频闪。",
    mainImage: "https://placehold.co/800x800?text=Reading+Lamp",
    price: 299,
    finalPrice: 219,
    couponAmount: 80,
    commissionRate: 7.6,
    shopName: "天猫儿童学习用品店",
    categoryId: "cat-parenting",
    categorySlug: "cat-parenting",
    categoryName: "母婴学习",
    promotionUrl: "https://example.com/promotion/mock-product-005",
    couponUrl: "https://example.com/coupon/mock-product-005",
    status: "draft",
    createdAt: "2026-06-20T08:20:00.000Z",
    updatedAt: "2026-06-20T08:20:00.000Z",
  },
  {
    id: "mock-product-006",
    platform: "other",
    source: "mock",
    outerItemId: "other-mock-100006",
    title: "便携式筋膜放松按摩器 运动后肌肉放松礼盒装",
    shortTitle: "便携筋膜按摩器",
    description: "面向运动恢复和日常放松场景，体积小、档位清晰，适合做礼品清单推荐。",
    mainImage: "https://placehold.co/800x800?text=Massage+Device",
    price: 199,
    finalPrice: 149,
    couponAmount: 50,
    commissionRate: 9.3,
    shopName: "精选健康生活馆",
    categoryId: "cat-health",
    categorySlug: "cat-health",
    categoryName: "个护健康",
    promotionUrl: "https://example.com/promotion/mock-product-006",
    couponUrl: "https://example.com/coupon/mock-product-006",
    status: "inactive",
    createdAt: "2026-06-20T08:25:00.000Z",
    updatedAt: "2026-06-20T08:25:00.000Z",
  },
];
