export type DataokeProductSchemaPlan = {
  brandId?: string;
  brandName?: string;
  categoryId: string;
  categoryName: string;
  categorySlug: string;
  commissionRate: number;
  couponAmount: number;
  couponConditions?: string;
  couponEndTime?: string;
  couponReceiveNum?: number;
  couponRemainCount?: number;
  couponStartTime?: string;
  couponTotalNum?: number;
  createdAt: string;
  dailySales?: number;
  dataokeId?: string;
  description: string;
  finalPrice: number;
  goodsSign?: string;
  id: string;
  images?: string[];
  isManualEdited: boolean;
  isManualHidden: boolean;
  lastSyncedAt?: string;
  mainImage: string;
  manualCategoryLocked: boolean;
  monthSales?: number;
  outerItemId: string;
  platform: string;
  price: number;
  shopLogo?: string;
  shopName: string;
  shortTitle: string;
  source: string;
  sourceCid?: string;
  sourceSubcid?: string;
  status: string;
  title: string;
  twoHoursSales?: number;
  updatedAt: string;
};

export type DataokePromotionLinkSchemaPlan = {
  actualPrice?: number;
  couponEndTime?: string;
  couponInfo?: string;
  couponRemainCount?: number;
  couponStartTime?: string;
  couponTotalCount?: number;
  couponUrl: string;
  createdAt: string;
  expiresAt?: string;
  id: string;
  lastGeneratedAt?: string;
  longTpwd?: string;
  maxCommissionRate?: number;
  minCommissionRate?: number;
  originalPrice?: number;
  outerItemId: string;
  platform: string;
  productId: string;
  promotionUrl: string;
  shortUrl?: string;
  source: string;
  status: string;
  tpwd: string;
  updatedAt: string;
};

export type DataokeSourceCategoryMappingSchemaPlan = {
  categoryId: string;
  categorySlug: string;
  confidence: string;
  createdAt: string;
  id: string;
  source: string;
  sourceCid: string;
  sourceName: string;
  sourceSubcid?: string;
  sourceSubName?: string;
  status: string;
  updatedAt: string;
};

export type DataokeSyncLogSchemaPlan = {
  createdAt: string;
  createdCount: number;
  errorSummary?: Record<string, unknown>;
  failedCount: number;
  finishedAt?: string;
  id: string;
  message?: string;
  params?: Record<string, unknown>;
  skippedCount: number;
  source: string;
  startedAt: string;
  status: string;
  successCount: number;
  taskType: string;
  totalCount: number;
  updatedCount: number;
};
